name: Gerador Matter NVS
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/esp-matter:latest
    steps:
      - name: Preparar Pastas
        run: mkdir -p /tmp/matter-out
      - name: Gerar Placa 1
        run: |
          cd /opt/esp/esp-matter/tools/mfg_tool
          python3 mfg_tool.py -n 1 -v 0xFFF1 -p 0x8001 --passcode 20202021 --discriminator 3840
          mv out/1 /tmp/matter-out/Placa_1
          rm -rf out
      - name: Gerar Placa 2
        run: |
          cd /opt/esp/esp-matter/tools/mfg_tool
          python3 mfg_tool.py -n 1 -v 0xFFF1 -p 0x8001 --passcode 20202021 --discriminator 3841
          mv out/1 /tmp/matter-out/Placa_2
          rm -rf out
      - name: Gerar Placa 3
        run: |
          cd /opt/esp/esp-matter/tools/mfg_tool
          python3 mfg_tool.py -n 1 -v 0xFFF1 -p 0x8001 --passcode 20202021 --discriminator 3842
          mv out/1 /tmp/matter-out/Placa_3
          rm -rf out
      - name: Gerar Placa 4
        run: |
          cd /opt/esp/esp-matter/tools/mfg_tool
          python3 mfg_tool.py -n 1 -v 0xFFF1 -p 0x8001 --passcode 20202021 --discriminator 3843
          mv out/1 /tmp/matter-out/Placa_4
      - name: Baixar Arquivos
        uses: actions/upload-artifact@v4
        with:
          name: Certificados_Matter
          path: /tmp/matter-out/
