name: Gerar Matter NVS
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    container: espressif/esp-matter:latest
    steps:
      - name: Achar e Rodar a Ferramenta
        shell: bash
        run: |
          # Instalar dependências
          python3 -m pip install pyqrcode pypng cryptography ecdsa --break-system-packages
          
          # Acha a pasta onde o mfg_tool.py realmente está escondido
          TOOL_PATH=$(find / -name "mfg_tool.py" -type f 2>/dev/null | head -n 1)
          TOOL_DIR=$(dirname "$TOOL_PATH")
          echo "Ferramenta encontrada em: $TOOL_PATH"
          
          # Entra na pasta e gera as 4 placas
          cd "$TOOL_DIR"
          
          python3 mfg_tool.py -n 1 -v 0xFFF1 -p 0x8001 --passcode 20202021 --discriminator 3840 && mv out/1 /tmp/Placa_1
          python3 mfg_tool.py -n 1 -v 0xFFF1 -p 0x8001 --passcode 20202021 --discriminator 3841 && mv out/1 /tmp/Placa_2
          python3 mfg_tool.py -n 1 -v 0xFFF1 -p 0x8001 --passcode 20202021 --discriminator 3842 && mv out/1 /tmp/Placa_3
          python3 mfg_tool.py -n 1 -v 0xFFF1 -p 0x8001 --passcode 20202021 --discriminator 3843 && mv out/1 /tmp/Placa_4
          
          mkdir -p /tmp/matter-out && mv /tmp/Placa_* /tmp/matter-out/
          
      - name: Baixar Arquivos
        uses: actions/upload-artifact@v4
        with:
          name: Certificados_Matter
          path: /tmp/matter-out/
