name: Gerar Matter NVS
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    container: espressif/esp-matter:latest
    steps:
      - name: Preparar Pastas
        run: mkdir -p /tmp/matter-out
        
      - name: Encontrar e Gerar Placas
        shell: bash
        run: |
          # 1. Instalar as bibliotecas do Python que a Espressif esqueceu de colocar no container
          python3 -m pip install pyqrcode pypng cryptography ecdsa --break-system-packages || true
          
          # 2. Achar a pasta real do esp-matter
          MATTER_ROOT=$(find /opt -type d -name "esp-matter" 2>/dev/null | head -n 1)
          echo "Pasta raiz do Matter encontrada em: $MATTER_ROOT"
          
          # 3. Ativar as variaveis e entrar na pasta da ferramenta
          cd $MATTER_ROOT
          source export.sh || true
          cd tools/mfg_tool
          
          # 4. Gerar Placa 1
          python3 mfg_tool.py -n 1 -v 0xFFF1 -p 0x8001 --passcode 20202021 --discriminator 3840
          mv out/1 /tmp/matter-out/Placa_1
          rm -rf out
          
          # 5. Gerar Placa 2
          python3 mfg_tool.py -n 1 -v 0xFFF1 -p 0x8001 --passcode 20202021 --discriminator 3841
          mv out/1 /tmp/matter-out/Placa_2
          rm -rf out
          
          # 6. Gerar Placa 3
          python3 mfg_tool.py -n 1 -v 0xFFF1 -p 0x8001 --passcode 20202021 --discriminator 3842
          mv out/1 /tmp/matter-out/Placa_3
          rm -rf out
          
          # 7. Gerar Placa 4
          python3 mfg_tool.py -n 1 -v 0xFFF1 -p 0x8001 --passcode 20202021 --discriminator 3843
          mv out/1 /tmp/matter-out/Placa_4
          
      - name: Baixar Arquivos
        uses: actions/upload-artifact@v4
        with:
          name: Certificados_Matter
          path: /tmp/matter-out/
